### ISSUE TITLE
Task #174 for SpiritsUnchained vDEV - 9

### ISSUE THREAD

**Issue by pump61** [JustAHuman-xD/SpiritsUnchained#10]
[15:31:06 WARN]: [SpiritsUnchained] Task #174 for SpiritsUnchained vDEV - 9 (git d46f05f8) generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.Location.distance(Location.java:493) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at me.justahuman.spiritsunchained.utils.SpiritUtils.getNearbySpirits(SpiritUtils.java:312) ~[SpiritsUnchained - DEV 4 (git f93da).jar:?]
        at me.justahuman.spiritsunchained.managers.SpiritEntityManager.spawnTick(SpiritEntityManager.java:83) ~[SpiritsUnchained - DEV 4 (git f93da).jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-270]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-270]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by pump61** [comment]
Paper git-Paper-270 (MC: 1.19.2)
Slimefun DEV - 1035 (git 0b7c656d)
Metrics-Module #28
Java 17
Installed Addons: (35)
  Networks vDEV - 45 (git ade6fbd0)
  CrystamaeHistoria vDEV - 78 (git 340f1a94)
  ExtraTools vDEV - 36 (git 922c0324)
  AureliumSkills vBeta 1.3.7
  ShopGUIPlus v1.80.1
  RelicsOfCthonia vDEV - 7 (git 5e498434)
  FoxyMachines vDEV - 60 (git b0ae0062)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  FNAmplifications vDEV - 80 (git 8c9eedc9)
  SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)
  AdvancedEnchantments v8.11.8
  ExtraGear vDEV - 13 (git c62047e2)
  DyeBench vDEV - 6 (git ae841c2d)
  Supreme vDEV - 16 (git 56737933)
  InfinityExpansion vDEV - 140 (git 0098d2fb)
  CMILib v1.2.3.7
  SFCalc vDEV - 37 (git dfc0fc41)
  RedProtect v8.0.0-SNAPSHOT
  CompressionCraft vDEV - 24 (git c8f3dcc1)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  DankTech v1.2.11
  FlowerPower vDEV - 15 (git 35662ced)
  SpiritsUnchained vDEV - 9 (git d46f05f8)
  ColoredEnderChests vDEV - 23 (git 4d041832)
  FluffyMachines vDEV - 127 (git cf047dcf)
  Brewery v3.1.1
  DyedBackpacks vDEV - 17 (git 8b329e96)
  AlchimiaVitae vDEV - 22 (git 09618c12)
  EcoPower vDEV - 5 (git 5c1ecd68)
  HotbarPets vDEV - 38 (git fa6c871d)
  Liquid vDEV - 14 (git 0f5346bf)
  LiteXpansion vDEV - 182 (git d3800398)
  SimpleUtils vDEV - 15 (git 4250fd5e)
  ElementManipulation vDEV - 28 (git 2b469991)
  PotionExpansion vDEV - 5 (git e2cfcd8a)

**Comment by JustAHuman-xD** [comment]
Ah will push a fix real soon

**Comment by JustAHuman-xD** [comment]
Pushed a fix, next build should contain it
